networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: S3nh4F0rt3!
    ports:
      - "5432:5432"
    volumes:
      - .src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fastfood
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=S3nh4F0rt3!
    depends_on:
      - postgres
    networks:
      - app-network