apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
  namespace: prod
  labels:
    app: fastfood-app
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-app
  template:
    metadata:
      name: fastfood-app
      labels:
        app: fastfood-app
        environment: prod
    spec:
      containers:
        - name: fastfood-app
          image: ${ECR_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/fastfood-terraform-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: configmap-fastfood
            - secretRef:
                name: secret-fastfood

      restartPolicy: Always