name: CI/CD Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Package
        run: mvn package
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          package:  '.*jar'
      - name: Publish package
        run: mvn --batch-mode deploy
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
